### ISSUE TITLE
False-positive E1133 (not-an-iterable) for iterable field

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/pylint-conf#65]
A code like this:

`for invoice in self.move_ids:`

Which is perfectly valid, generates the following error:

`Non-iterable value self.move_ids is used in an iterating context`

It seems this lint isn't able to know that `move_ids` is an iterable, despite being an attribute (one2many field).

**Comment by moylop260** [comment]
Could you share the pipeline URL where it is reproduced, please?

**Comment by luisg123v** [comment]
[Here](https://git.vauxoo.com/vauxoo/petroil/-/jobs/548575) the pipeline.

CC @suniagajose

**Comment by moylop260** [comment]
I can't reproduce it using the same branch.

In fact, the last pipeline the lint is green:
 - https://git.vauxoo.com/vauxoo/petroil/-/jobs/548683

Check the pipeline of the MR:
 - https://git.vauxoo.com/vauxoo/petroil/-/merge_requests/39

If you can reproduce it again just re-open it, please

**Comment by luisg123v** [comment]
@moylop260 I was able to replicate it by:
- Going to the commit referenced in the failed pipeline
- Creating a new branch using that commit through the GitLab's interface

At that point, it was replicated, but I created [this MR](https://git.vauxoo.com/vauxoo/petroil/-/merge_requests/48) with only the involved file.

Since I could replicate it, I'll reopen.

**Comment by fernandahf** [comment]
@luisg123v, @moylop260 

According to research in same project that @luisg123v tested, the problem is that in same class where is checked lint, there is  onchange method that set move_ids to False (to clean it), I had review and if I remove those lines (where move_ids is set), lint does not appear and also correct way to clean move_ids is:

`self.move_ids = [(5, )]
`

Therefore, I think that this issue must be closed because pylint is not the problem.

cc @suniagajose 

Regards.

**Comment by luisg123v** [comment]
Thanks a lot @fernandahf.

I'll close this issue..
